#!/usr/bin/env Rscript
# Parametric bootstrap power test for MAST tree-number (K) selection.
#
# This mirrors the core analysis exactly. For a gap threshold t whose core
# BIC sweep selected K* trees (0.1 -> 4, 0.5 -> 6, 0.9 -> 5), the test asks a
# single question: if the data really were generated by that K* MAST model,
# how often does the same BIC model-selection procedure recover K*?
#
# Steps:
#   1. Read the fitted K* MAST model from the core output: the linked GTR
#      substitution parameters, the FreeRate (R4) categories, the K* tree
#      weights, and the K* fitted trees with their branch lengths.
#   2. Simulate B replicate alignments under that model with IQ-TREE's AliSim.
#      Each site is assigned to a tree class by the fitted weights and evolved
#      along that class tree under the shared GTR+FO+R4 process.
#   3. Refit MAST for k = K_MIN..K_MAX on every replicate, reusing the same
#      candidate-tree subsets (generated/<t>/tree_subsets/modeltrees_final_k)
#      and the identical call: iqtree3 -m "GTR+FO+R4+T" -te <subset> -wspmr
#      -wslmr. Only the input alignment differs from the core sweep.
#   4. Record the BIC-minimising k per replicate and report the power to
#      recover K*.
#
# Usage:  Rscript power_bootstrap/power_bootstrap.R <threshold>
#         threshold in {0.1, 0.5, 0.9}
#
# Environment overrides (for quick validation runs):
#   PB_B, PB_KMIN, PB_KMAX, PB_NCORES, PB_NT, PB_SEED

suppressMessages({
  library(here)
  library(ape)
  library(parallel)
})
here::i_am("power_bootstrap/power_bootstrap.R")

## ---- configuration -------------------------------------------------------

# Resolve the IQ-TREE 3 executable, in order of preference:
#   1. the PB_IQTREE environment variable (explicit path),
#   2. iqtree3 then iqtree2 on PATH (e.g. after `module load iqtree` on a cluster),
#   3. the local macOS build used during development.
resolve_iqtree <- function() {
  v <- Sys.getenv("PB_IQTREE")
  if (nzchar(v)) return(v)
  for (b in c("iqtree3", "iqtree2")) {
    w <- Sys.which(b); if (nzchar(w)) return(unname(w))
  }
  mac <- "/Users/ctf150/Desktop/Software/iqtree-3.0.1-macOS/bin/iqtree3"
  if (file.exists(mac)) return(mac)
  stop("IQ-TREE not found. Set PB_IQTREE=/path/to/iqtree3 or put iqtree3 on PATH.")
}
IQTREE <- resolve_iqtree()

env_int <- function(name, default) {
  v <- Sys.getenv(name); if (nzchar(v)) as.integer(v) else default
}

args      <- commandArgs(trailingOnly = TRUE)
THRESHOLD <- if (length(args) >= 1) args[1] else "0.1"

B       <- env_int("PB_B", 100L)
K_MIN   <- env_int("PB_KMIN", 2L)
K_MAX   <- env_int("PB_KMAX", 10L)
# Default to all detected cores, one thread per fit (best throughput for many
# small independent fits). Override with PB_NCORES / PB_NT on the target machine.
N_CORES <- env_int("PB_NCORES", max(1L, parallel::detectCores()))  # concurrent fits
NT      <- env_int("PB_NT", 1L)                                    # threads per fit
SEED    <- env_int("PB_SEED", 1L)

# Core-selected best K per threshold (argmin BIC over k=2..35).
BEST_K <- list("0.1" = 4L, "0.5" = 6L, "0.9" = 5L)
# The core output directory names are inconsistent for 0.5.
ODIR   <- list("0.1" = "0.1", "0.5" = "0.5_output", "0.9" = "0.9")

if (is.null(BEST_K[[THRESHOLD]]))
  stop("Unknown threshold: ", THRESHOLD, " (expected 0.1, 0.5, or 0.9)")

KSTAR    <- BEST_K[[THRESHOLD]]
odir     <- ODIR[[THRESHOLD]]
FASTA    <- here("data", paste0(THRESHOLD, "_trimmed_alns_HIV_2021_subset.fasta"))
BEST_DIR <- here("output", odir, paste0("mast_model_", KSTAR))
BEST_IQ  <- file.path(BEST_DIR, paste0("mast_model_final_", KSTAR, ".iqtree"))
BEST_TRE <- file.path(BEST_DIR, paste0("mast_model_final_", KSTAR, ".treefile"))
SUBSET   <- function(k) here("generated", THRESHOLD, "tree_subsets",
                             paste0("modeltrees_final_", k, ".newick"))

OUTDIR <- here("power_bootstrap", "results", THRESHOLD)
SIMDIR <- file.path(OUTDIR, "sims")
FITDIR <- file.path(OUTDIR, "refits")
for (d in c(OUTDIR, SIMDIR, FITDIR)) dir.create(d, recursive = TRUE, showWarnings = FALSE)

for (f in c(FASTA, BEST_IQ, BEST_TRE)) if (!file.exists(f)) stop("Missing: ", f)
for (k in K_MIN:K_MAX) if (!file.exists(SUBSET(k))) stop("Missing candidate trees: ", SUBSET(k))

message("IQ-TREE: ", IQTREE)
message(sprintf("[%s] K* = %d | B = %d | k = %d..%d | trees fixed (-te), BLs re-optimised",
                THRESHOLD, KSTAR, B, K_MIN, K_MAX))

## ---- parse the fitted K* model ------------------------------------------

iq <- readLines(BEST_IQ)

# Linked GTR exchangeabilities, in AliSim order AC/AG/AT/CG/CT/GT.
# These lines use a colon: "  A-C: 1.8543".
grab <- function(tag) as.numeric(sub(paste0(".*", tag, ":\\s*"), "",
                                     grep(paste0(tag, ":"), iq, value = TRUE)[1]))
rate_params <- c(grab("A-C"), grab("A-G"), grab("A-T"),
                 grab("C-G"), grab("C-T"), grab("G-T"))

# ML base frequencies. These lines use an equals sign: "  pi(A) = 0.3937".
grab_eq <- function(tag) as.numeric(sub(paste0(".*", tag, "\\s*=\\s*"), "",
                                        grep(tag, iq, value = TRUE)[1]))
freqs <- c(grab_eq("pi\\(A\\)"), grab_eq("pi\\(C\\)"),
           grab_eq("pi\\(G\\)"), grab_eq("pi\\(T\\)"))

# FreeRate categories: "Site proportion and rates:  (p,r) (p,r) ..."
prop_line <- grep("Site proportion and rates:", iq, value = TRUE)[1]
pairs <- regmatches(prop_line,
  gregexpr("\\(([0-9.eE+-]+),([0-9.eE+-]+)\\)", prop_line))[[1]]
rate_cats <- lapply(pairs, function(p)
  as.numeric(strsplit(gsub("[()]", "", p), ",")[[1]]))  # c(proportion, rate)

# Tree weights.
w_line  <- grep("^Tree weights:", iq, value = TRUE)[1]
weights <- as.numeric(strsplit(sub("^Tree weights:\\s*", "", w_line), ",\\s*")[[1]])

# Alignment length.
n_line  <- grep("nucleotide sites", iq, value = TRUE)[1]
NSITES  <- as.integer(sub(".*with\\s+([0-9]+)\\s+nucleotide sites.*", "\\1", n_line))

stopifnot(length(weights) == KSTAR, length(rate_cats) == 4, length(freqs) == 4)
if (anyNA(c(rate_params, freqs, weights, unlist(rate_cats), NSITES)))
  stop("Failed to parse one or more fitted parameters from ", BEST_IQ)

# AliSim model string, matching the tested kpower format:
#   GTR{ac/ag/at/cg/ct/gt}+FU{fa/fc/fg/ft}+R4{p1/r1/p2/r2/p3/r3/p4/r4}
alisim_model <- paste0(
  "GTR{", paste(rate_params, collapse = "/"), "}",
  "+FU{", paste(freqs, collapse = "/"), "}",
  "+R", length(rate_cats), "{",
  paste(vapply(rate_cats, function(c) paste(c[1], c[2], sep = "/"), character(1)),
        collapse = "/"), "}")

message("  fitted model: ", alisim_model)
message("  tree weights: ", paste(round(weights, 4), collapse = ", "))

# The K* trees, one Newick string per line, with fitted branch lengths.
trees <- readLines(BEST_TRE)
trees <- trees[nzchar(trims <- trimws(trees))]
stopifnot(length(trees) == KSTAR)

## ---- step 1: simulate B replicates --------------------------------------

run <- function(args, stdout = FALSE) {
  system2(IQTREE, args, stdout = if (stdout) TRUE else FALSE, stderr = FALSE)
}

simulate_replicate <- function(b) {
  set.seed(SEED + b)
  counts <- as.vector(rmultinom(1, size = NSITES, prob = weights))  # sites per class
  blocks <- vector("list", KSTAR)
  repdir <- file.path(SIMDIR, sprintf("rep_%03d", b))
  dir.create(repdir, showWarnings = FALSE)

  for (k in seq_len(KSTAR)) {
    if (counts[k] == 0) next
    treef <- file.path(repdir, sprintf("class_%d.nwk", k))
    writeLines(trees[k], treef)
    pre   <- file.path(repdir, sprintf("class_%d", k))
    run(c("--alisim", pre, "-t", treef, "-m", shQuote(alisim_model),
          "--length", counts[k], "-seed", SEED + b * 100 + k,
          "-af", "fasta", "-nt", "1"))
    fa <- paste0(pre, ".fa")
    if (!file.exists(fa)) fa <- paste0(pre, ".fasta")
    blocks[[k]] <- as.matrix(read.dna(fa, format = "fasta"))
  }

  blocks <- blocks[!vapply(blocks, is.null, logical(1))]
  taxa   <- rownames(blocks[[1]])
  aln    <- do.call(cbind, lapply(blocks, function(m) m[taxa, , drop = FALSE]))
  repfa  <- file.path(SIMDIR, sprintf("rep_%03d.fasta", b))
  write.dna(aln, repfa, format = "fasta", nbcol = -1, colsep = "")
  unlink(repdir, recursive = TRUE)
  repfa
}

message("Simulating ", B, " replicate alignments of ", NSITES, " sites ...")
sim_files <- vapply(seq_len(B), simulate_replicate, character(1))

## ---- step 2: refit k = K_MIN..K_MAX on every replicate ------------------

parse_bic <- function(iqfile) {
  ln <- grep("Bayesian information criterion \\(BIC\\) score:",
             readLines(iqfile), value = TRUE)[1]
  as.numeric(sub(".*score:\\s*", "", ln))
}

fit_one <- function(job) {
  b <- job$b; k <- job$k
  pre <- file.path(FITDIR, sprintf("rep_%03d_k%d", b, k))
  run(c("-s", sim_files[b], "-m", "GTR+FO+R4+T", "-te", SUBSET(k),
        "--prefix", pre, "-nt", NT, "-wspmr", "-wslmr", "-redo"))
  iqf <- paste0(pre, ".iqtree")
  data.frame(rep = b, k = k,
             BIC = if (file.exists(iqf)) parse_bic(iqf) else NA_real_)
}

jobs <- do.call(rbind, lapply(seq_len(B), function(b)
  data.frame(b = b, k = K_MIN:K_MAX)))
jobs <- split(jobs, seq_len(nrow(jobs)))

message("Refitting ", length(jobs), " MAST models (",
        N_CORES, " concurrent, ", NT, " threads each) ...")
res <- mclapply(jobs, fit_one, mc.cores = N_CORES)
bic <- do.call(rbind, res)

## ---- step 3: recovered K per replicate and power ------------------------

recovered <- do.call(rbind, lapply(split(bic, bic$rep), function(d) {
  d <- d[!is.na(d$BIC), ]
  data.frame(rep = d$rep[1], recovered_K = d$k[which.min(d$BIC)])
}))
power <- mean(recovered$recovered_K == KSTAR)

write.csv(bic, file.path(OUTDIR, paste0("bic_by_rep_", THRESHOLD, ".csv")), row.names = FALSE)
write.csv(recovered, file.path(OUTDIR, paste0("recovered_K_", THRESHOLD, ".csv")), row.names = FALSE)

tab <- table(factor(recovered$recovered_K, levels = K_MIN:K_MAX))
summary_txt <- c(
  sprintf("Threshold %s: core-selected K* = %d", THRESHOLD, KSTAR),
  sprintf("Replicates: %d | refit range k = %d..%d", nrow(recovered), K_MIN, K_MAX),
  sprintf("Power to recover K* under BIC: %.1f%%", 100 * power),
  "Distribution of recovered K:",
  paste(capture.output(print(tab)), collapse = "\n"))
writeLines(summary_txt, file.path(OUTDIR, paste0("power_summary_", THRESHOLD, ".txt")))
message(paste(summary_txt, collapse = "\n"))

pdf(file.path(OUTDIR, paste0("recovered_K_", THRESHOLD, ".pdf")), width = 7, height = 5)
barplot(tab, xlab = "Recovered number of trees (K)", ylab = "Replicates",
        main = sprintf("Threshold %s: power to recover K* = %d is %.1f%%",
                       THRESHOLD, KSTAR, 100 * power))
abline(v = NA)
dev.off()

message("[", THRESHOLD, "] done. Results in ", OUTDIR)
